# Generated by Django 4.1.5 on 2023-03-31 19:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0004_cartitem_is_paid_alter_cartitem_image_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartitem',
            name='is_paid',
        ),
    ]
